#ifndef DRIVERSCONTAINER_CONFIG_H
#define DRIVERSCONTAINER_CONFIG_H

#define ENCODER_MASTER_GPIO		1
#define ENCODER_SLAVE_GPIO		2

#define MOTOR_MASTER_PWM_GPIO	3
#define MOTOR_MASTER_DIR_GPIO	4
#define MOTOR_MASTER_ENB_GPIO	5

#define MOTOR_SLAVE_PWM_GPIO	6
#define MOTOR_SLAVE_DIR_GPIO	7
#define MOTOR_SLAVE_ENB_GPIO	8

#define MOTOR_CUTTER_DIR_GPIO	10
#define MOTOR_CUTTER_PWM_GPIO	11
#define RELAY_CUTTER_ENB_GPIO	12
#define RELAY_ELECTROVALVES_GPIO	16

#define SENSOR_INIT_HORIZONTAL_GPIO	13
#define SENSOR_INIT_VERTICAL_GPIO	14
#define SENSOR_LASER_CUT_GPIO		15

#define LED_TRAFFIC				21
#define LED_CONNECTION			22

#define TCP_ACK_INTERVAL_MS		3000

#endif //DRIVERSCONTAINER_CONFIG_H
